# Site settings
title: Carter F. 
email: contact@carterfendley.com
description: Carter F. is a student of Computer Science and Robotics
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site

# Identity
your-name: Carter Fendley
your-title: Computer Science Student

# Social settings
500px_url:
facebook_url: 
github_url: https://github.com/CarterFendley
gitlab_url: 
googleplus_url: 
instagram_url: 
linkedin_url: https://www.linkedin.com/in/carter-f-260473121/
pinterest_url:
slack_url:
twitter_url: 

# Build settings
markdown: kramdown
